### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by michalcerny** [nishanthvijayan/wakatime-tracker#2]
Hey! I did everyting in tutorial but getting this error, anything I can do with it?

Thanks!

![snimek obrazovky 2018-11-07 v 14 12 10](https://user-images.githubusercontent.com/31419790/48133475-24321080-e297-11e8-910a-ac71673591ea.png)

**Comment by michalcerny** [comment]
It works if I remove "async" from getCodingTime function 👍

**Comment by nishanthvijayan** [comment]
Which version of nodejs do you have installed in your system?

**Comment by nishanthvijayan** [comment]
Doesn't matter. async is not necessary there anyway. I'll take it away. Thanks for reporting this.

**Comment by nishanthvijayan** [comment]
Fixed in commit ed0dda5c677bb8b919458d5399a600deb371cf26
